# ShopPlugin Configuration
# -----------------------
#
# This file contains all the settings for the shop plugin.
# You can customize categories, items, and pricing here.

# General settings
settings:
  # Should the shop auto-open for players when they first join?
  open-on-join: false

  # Default starting money for mock economy (only used if Vault isn't available)
  default-balance: 1000.0

  # Maximum quantity that can be purchased in a single transaction
  max-purchase-quantity: 64

# Categories and items
categories:
  blocks:
    name: "Building Blocks"
    icon: "B"
    items:
      stone:
        name: "Stone"
        material: "STONE"
        buy-price: 2.0
        sell-price: 1.0
        description: "A common building material"

      dirt:
        name: "Dirt"
        material: "DIRT"
        buy-price: 1.0
        sell-price: 0.5
        description: "The most common block in Minecraft"

      cobblestone:
        name: "Cobblestone"
        material: "COBBLESTONE"
        buy-price: 1.5
        sell-price: 0.7
        description: "A rugged building material"

      brick:
        name: "Bricks"
        material: "BRICK"
        buy-price: 10.0
        sell-price: 5.0
        description: "Decorative red brick blocks"

  ores:
    name: "Ores & Resources"
    icon: "O"
    items:
      coal:
        name: "Coal"
        material: "COAL"
        buy-price: 8.0
        sell-price: 4.0
        description: "Used as fuel"

      iron_ingot:
        name: "Iron Ingot"
        material: "IRON_INGOT"
        buy-price: 20.0
        sell-price: 10.0
        description: "Used to craft tools and armor"

      gold_ingot:
        name: "Gold Ingot"
        material: "GOLD_INGOT"
        buy-price: 40.0
        sell-price: 20.0
        description: "Shiny and valuable"

      diamond:
        name: "Diamond"
        material: "DIAMOND"
        buy-price: 100.0
        sell-price: 50.0
        description: "The most valuable gem"

      emerald:
        name: "Emerald"
        material: "EMERALD"
        buy-price: 80.0
        sell-price: 40.0
        description: "Trading currency with villagers"

      lapis_lazuli:
        name: "Lapis Lazuli"
        material: "LAPIS_ORE"
        buy-price: 15.0
        sell-price: 7.5
        description: "Used for enchanting"

      redstone:
        name: "Redstone Dust"
        material: "REDSTONE"
        buy-price: 10.0
        sell-price: 5.0
        description: "Used for redstone circuits"

      quartz:
        name: "Nether Quartz"
        material: "QUARTZ"
        buy-price: 15.0
        sell-price: 7.5
        description: "White crystal from the Nether"

  tools:
    name: "Tools & Weapons"
    icon: "T"
    items:
      iron_sword:
        name: "Iron Sword"
        material: "IRON_SWORD"
        buy-price: 50.0
        sell-price: 20.0
        description: "Standard combat weapon"

      diamond_sword:
        name: "Diamond Sword"
        material: "DIAMOND_SWORD"
        buy-price: 200.0
        sell-price: 80.0
        description: "High-tier combat weapon"

      iron_pickaxe:
        name: "Iron Pickaxe"
        material: "IRON_PICKAXE"
        buy-price: 60.0
        sell-price: 20.0
        description: "Standard mining tool"

      diamond_pickaxe:
        name: "Diamond Pickaxe"
        material: "DIAMOND_PICKAXE"
        buy-price: 220.0
        sell-price: 80.0
        description: "High-tier mining tool"

      iron_axe:
        name: "Iron Axe"
        material: "IRON_AXE"
        buy-price: 60.0
        sell-price: 20.0
        description: "Wood cutting tool"

      iron_spade:
        name: "Iron Spade"
        material: "IRON_SPADE"
        buy-price: 40.0
        sell-price: 15.0
        description: "Digging tool"

      bow:
        name: "Bow"
        material: "BOW"
        buy-price: 30.0
        sell-price: 10.0
        description: "Ranged weapon"

      shield:
        name: "Shield"
        material: "SHIELD"
        buy-price: 70.0
        sell-price: 25.0
        description: "Blocking tool for combat"

  food:
    name: "Food & Farming"
    icon: "F"
    items:
      bread:
        name: "Bread"
        material: "BREAD"
        buy-price: 6.0
        sell-price: 3.0
        description: "Basic food item"

      cooked_beef:
        name: "Steak"
        material: "COOKED_BEEF"
        buy-price: 10.0
        sell-price: 5.0
        description: "High-quality food item"

      apple:
        name: "Apple"
        material: "APPLE"
        buy-price: 4.0
        sell-price: 2.0
        description: "Basic fruit"

      golden_apple:
        name: "Golden Apple"
        material: "GOLDEN_APPLE"
        buy-price: 150.0
        sell-price: 75.0
        description: "Special food with regeneration"

      cake:
        name: "Cake"
        material: "CAKE"
        buy-price: 50.0
        sell-price: 25.0
        description: "Placeable food item"

      carrot:
        name: "Carrot"
        material: "CARROT"
        buy-price: 3.0
        sell-price: 1.5
        description: "Vegetable food and crop"

      potato:
        name: "Potato"
        material: "POTATO"
        buy-price: 3.0
        sell-price: 1.5
        description: "Can be eaten or planted"

  decorations:
    name: "Decorations"
    icon: "D"
    items:
      flower_pot:
        name: "Flower Pot"
        material: "FLOWER_POT"
        buy-price: 10.0
        sell-price: 5.0
        description: "Decorative container for plants"

      painting:
        name: "Painting"
        material: "PAINTING"
        buy-price: 15.0
        sell-price: 7.5
        description: "Wall decoration"

      item_frame:
        name: "Item Frame"
        material: "ITEM_FRAME"
        buy-price: 12.0
        sell-price: 6.0
        description: "Display items on walls"

      bookshelf:
        name: "Bookshelf"
        material: "BOOKSHELF"
        buy-price: 30.0
        sell-price: 15.0
        description: "Decorative storage"

      lantern:
        name: "Lantern"
        material: "JACK_O_LANTERN"
        buy-price: 25.0
        sell-price: 12.5
        description: "Hanging light source"

      torch:
        name: "Torch"
        material: "TORCH"
        buy-price: 5.0
        sell-price: 2.5
        description: "Basic light source"

      sea_lantern:
        name: "Sea Lantern"
        material: "SEA_LANTERN"
        buy-price: 50.0
        sell-price: 25.0
        description: "Underwater light source"

      glowstone:
        name: "Glowstone"
        material: "GLOWSTONE"
        buy-price: 40.0
        sell-price: 20.0
        description: "Bright light source"

  redstone:
    name: "Redstone"
    icon: "R"
    items:
      redstone_torch:
        name: "Redstone Torch"
        material: "REDSTONE_TORCH_ON"
        buy-price: 15.0
        sell-price: 7.5
        description: "Provides weak redstone power"

      lever:
        name: "Lever"
        material: "LEVER"
        buy-price: 10.0
        sell-price: 5.0
        description: "Redstone switch"

      stone_button:
        name: "Stone Button"
        material: "STONE_BUTTON"
        buy-price: 8.0
        sell-price: 4.0
        description: "Momentary redstone signal"

      repeater:
        name: "Redstone Repeater"
        material: "DIODE"
        buy-price: 25.0
        sell-price: 12.5
        description: "Extends redstone signal"

      comparator:
        name: "Redstone Comparator"
        material: "REDSTONE_COMPARATOR_ON"
        buy-price: 30.0
        sell-price: 15.0
        description: "Compares signal strength"

      hopper:
        name: "Hopper"
        material: "HOPPER"
        buy-price: 60.0
        sell-price: 30.0
        description: "Moves items between containers"

  special:
    name: "Special Items"
    icon: "S"
    items:
      ender_pearl:
        name: "Ender Pearl"
        material: "ENDER_PEARL"
        buy-price: 40.0
        # Not sellable
        description: "Teleports player when thrown"
        max-purchase: 16  # Optional limit per transaction

      dragon_egg:
        name: "Dragon Egg"
        material: "DRAGON_EGG"
        buy-price: 10000.0
        # Not sellable
        description: "Ultra rare decorative item"
        max-purchase: 1  # Limit to one per transaction

      elytra:
        name: "Elytra"
        material: "ELYTRA"
        buy-price: 5000.0
        sell-price: 2000.0
        description: "Glider wings for flying"
        max-purchase: 1  # Limit to one per transaction

      beacon:
        name: "Beacon"
        material: "BEACON"
        buy-price: 2000.0
        sell-price: 1000.0
        description: "Provides status effects"
        max-purchase: 4  # Limit to four per transaction

      nether_star:
        name: "Nether Star"
        material: "NETHER_STAR"
        buy-price: 1500.0
        sell-price: 750.0
        description: "Crafting material for beacons"
        max-purchase: 16  # Limit per transaction

# Debugging
debug:
  # Log detailed information about transactions?
  enabled: false